import { Award, Star, Clock, BookOpen, TrendingUp, Download, CheckCircle2 } from "lucide-react";
import { CERTS, CPD_ACHIEVEMENTS, SKILLS_MATRIX } from "@/lib/cpdData";
import { jsPDF } from "jspdf";

const SPECIALISATIONS = [
  "Safeguarding Level 2+",
  "Therapeutic Parenting",
  "Attachment-Focused Care",
  "Fostering Legislation 2024",
];

export default function ProfessionalPassport({ userName = "Emma Clarke" }) {
  const totalHours = CERTS.reduce((s, c) => s + c.hours, 0);
  const validCerts = CERTS.filter(c => c.status === "valid").length;
  const earnedBadges = CPD_ACHIEVEMENTS.filter(a => a.earned);
  const overallSkill = (SKILLS_MATRIX.reduce((s, cat) => s + cat.skills.reduce((a, sk) => a + sk.level, 0) / cat.skills.length, 0) / SKILLS_MATRIX.length).toFixed(1);

  const handleDownload = () => {
    const doc = new jsPDF({ unit: "mm", format: "a4" });
    doc.setFillColor(15, 23, 42); doc.rect(0, 0, 210, 297, "F");
    doc.setFillColor(255, 255, 255); doc.roundedRect(10, 10, 190, 60, 5, 5, "F");
    doc.setFillColor(37, 99, 235); doc.roundedRect(20, 22, 30, 30, 3, 3, "F");
    doc.setTextColor(255, 255, 255); doc.setFont("helvetica", "bold"); doc.setFontSize(14);
    doc.text(userName.split(" ").map(w => w[0]).join(""), 35, 41, { align: "center" });
    doc.setTextColor(15, 23, 42); doc.setFontSize(16); doc.text(userName, 60, 30);
    doc.setFont("helvetica", "normal"); doc.setFontSize(10); doc.setTextColor(100, 116, 139);
    doc.text("Foster Carer · AAF CareConnect™ Professional Passport", 60, 39);
    doc.setFontSize(9);
    doc.text(`CPD Hours: ${totalHours}h  ·  Certificates: ${CERTS.length}  ·  Valid: ${validCerts}  ·  Badges: ${earnedBadges.length}`, 60, 50);
    doc.setFont("helvetica", "bold"); doc.setTextColor(255, 255, 255); doc.setFontSize(12);
    doc.text("Specialisations", 20, 90);
    SPECIALISATIONS.forEach((s, i) => {
      doc.setFont("helvetica", "normal"); doc.setFontSize(10); doc.setTextColor(200, 210, 230);
      doc.text(`• ${s}`, 25, 100 + i * 8);
    });
    doc.setFont("helvetica", "bold"); doc.setTextColor(255, 255, 255); doc.setFontSize(12);
    doc.text("Certificates", 110, 90);
    CERTS.slice(0, 8).forEach((c, i) => {
      doc.setFont("helvetica", "normal"); doc.setFontSize(9); doc.setTextColor(180, 195, 215);
      doc.text(`• ${c.title} (${c.hours}h)`, 115, 100 + i * 8);
    });
    doc.setFontSize(8); doc.setTextColor(100, 116, 139);
    doc.text(`Generated by AAF CareConnect™ · ${new Date().toLocaleDateString("en-GB")}`, 105, 285, { align: "center" });
    doc.save(`Professional_Passport_${userName.replace(" ", "_")}.pdf`);
  };

  return (
    <div className="space-y-5 animate-fade-in">
      {/* Passport card */}
      <div className="bg-gradient-to-br from-slate-900 via-slate-800 to-blue-950 rounded-2xl p-6 text-white relative overflow-hidden">
        {/* Decorative elements */}
        <div className="absolute top-0 right-0 w-64 h-64 bg-blue-600/10 rounded-full -translate-x-8 -translate-y-32" />
        <div className="absolute bottom-0 left-0 w-48 h-48 bg-violet-600/10 rounded-full translate-x-8 translate-y-24" />

        <div className="relative z-10">
          <div className="flex items-start justify-between mb-6">
            <div className="flex items-center gap-4">
              <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-blue-500 to-violet-600 flex items-center justify-center text-white font-heading font-bold text-xl shadow-lg shadow-blue-900/30">
                {userName.split(" ").map(w => w[0]).join("")}
              </div>
              <div>
                <p className="text-[10px] text-blue-400 font-bold uppercase tracking-widest mb-0.5">Professional Passport</p>
                <h2 className="font-heading font-bold text-xl text-white">{userName}</h2>
                <p className="text-sm text-slate-400">Foster Carer · Registered Professional</p>
              </div>
            </div>
            <div className="text-right">
              <p className="text-[9px] text-slate-500 uppercase tracking-wider">Issued by</p>
              <p className="text-xs font-bold text-blue-400">AAF CareConnect™</p>
              <p className="text-[9px] text-slate-500 mt-0.5">Ofsted-aligned</p>
            </div>
          </div>

          {/* Stats row */}
          <div className="grid grid-cols-4 gap-3 mb-6">
            {[
              { label: "CPD Hours", value: `${totalHours}h`, icon: Clock,    color: "text-blue-400"   },
              { label: "Certificates", value: CERTS.length, icon: Award,     color: "text-violet-400" },
              { label: "Badges", value: earnedBadges.length, icon: Star,     color: "text-amber-400"  },
              { label: "Skill Score", value: `${overallSkill}/5`, icon: TrendingUp, color: "text-emerald-400" },
            ].map(s => {
              const Icon = s.icon;
              return (
                <div key={s.label} className="bg-white/10 rounded-xl p-3 text-center backdrop-blur-sm">
                  <Icon size={16} className={`${s.color} mx-auto mb-1`} />
                  <p className="font-heading font-bold text-white text-lg leading-none">{s.value}</p>
                  <p className="text-[9px] text-slate-400 mt-0.5">{s.label}</p>
                </div>
              );
            })}
          </div>

          {/* Specialisations */}
          <div className="mb-4">
            <p className="text-[9px] text-slate-500 uppercase tracking-widest mb-2">Specialisations</p>
            <div className="flex flex-wrap gap-2">
              {SPECIALISATIONS.map(s => (
                <span key={s} className="text-[10px] font-semibold bg-blue-600/30 text-blue-300 border border-blue-600/30 rounded-full px-2.5 py-1">
                  {s}
                </span>
              ))}
            </div>
          </div>

          <button onClick={handleDownload} className="h-9 px-4 text-xs font-semibold bg-white/15 hover:bg-white/25 text-white rounded-xl flex items-center gap-2 transition-colors border border-white/10">
            <Download size={13} /> Download Passport PDF
          </button>
        </div>
      </div>

      {/* Achievement badges */}
      <div className="card p-5">
        <div className="flex items-center gap-2 mb-4">
          <Star size={15} className="text-amber-500" />
          <h3 className="text-sm font-bold text-slate-900">Achievement Badges</h3>
          <span className="ml-auto text-xs text-slate-400">{earnedBadges.length}/{CPD_ACHIEVEMENTS.length} earned</span>
        </div>
        <div className="grid grid-cols-4 gap-3">
          {CPD_ACHIEVEMENTS.map(a => (
            <div key={a.id} className={`rounded-xl p-3 text-center transition-all ${a.earned ? "bg-amber-50 border border-amber-200" : "bg-slate-50 border border-slate-100 opacity-50"}`}>
              <div className={`text-2xl mb-1 ${a.earned ? "" : "grayscale"}`}>{a.icon}</div>
              <p className={`text-[9px] font-bold leading-snug ${a.earned ? "text-amber-800" : "text-slate-400"}`}>{a.label}</p>
              {a.earned && <CheckCircle2 size={10} className="text-emerald-500 mx-auto mt-1" />}
            </div>
          ))}
        </div>
      </div>

      {/* Category breakdown */}
      <div className="card p-5">
        <div className="flex items-center gap-2 mb-4">
          <BookOpen size={15} className="text-blue-600" />
          <h3 className="text-sm font-bold text-slate-900">CPD by Category</h3>
        </div>
        <div className="space-y-3">
          {Object.entries(
            CERTS.reduce((acc, c) => { acc[c.category] = (acc[c.category] || 0) + c.hours; return acc; }, {})
          ).sort((a, b) => b[1] - a[1]).map(([cat, hrs]) => {
            const maxHrs = 12;
            const pct = Math.min((hrs / maxHrs) * 100, 100);
            return (
              <div key={cat} className="space-y-1">
                <div className="flex items-center justify-between">
                  <span className="text-xs text-slate-600 font-medium">{cat}</span>
                  <span className="text-xs font-bold text-slate-700">{hrs}h</span>
                </div>
                <div className="h-1.5 bg-slate-100 rounded-full overflow-hidden">
                  <div className="h-full bg-blue-600 rounded-full transition-all duration-700" style={{ width: `${pct}%` }} />
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}